### PR TITLE
tables for redactor

### PR DESCRIPTION
**Pull request by exomarty**
This will add tables plugin
Important: In order to actually see a nice table format once you submit message your theme will need table css additions.

I have this on my topic.less

//tables css

table
{
  font-size: 14px;
    border-collapse:collapse;
    margin:20px 0 0;
    padding:0;
}

table tr
{
    border-top:1px solid #ccc;
    background-color:#fff;
    margin:0;
    padding:0;
}

table tr:nth-child(2n)
{
    background-color:#f8f8f8;
}
table tr th[align="center"], table tr td[align="center"] {
    text-align:center;
}
table tr th, table tr td
{
    border:1px solid #ccc;
    text-align:left;
    margin:0;
    padding:6px 13px;
}

### CODE REVIEW

**Comment by yariplus** [comment]
Nice. Probably would be a good idea to apply the bootstrap table classes using the redactor's less file. Would result in better theme compatibility.

**Comment by drewdotpro** [comment]
First of all, thank you very much for the pull request. Your contribution to composer redactor looks really good.
Being that the redactor window has the same class definition as a topic, why is there the need for less here at all?

**Comment by yariplus** [comment]
@drewdotpro The less is needed because bootstrap needs the table tag to have the class="table"

So something like,

```
.redactor-editor { 
    table {
        .table;
    }
}
```

to apply the bootstrap styles.

**Comment by exomarty** [comment]
I added less in that override file cause i didnt want to edit redactor.less but you can add it whereever you want. Its same css lines as official redactor so i guess its better to keep the redactor way instead of using external code.

**Comment by exomarty** [comment]
Just notice your theme code to display tables on topics doesnt need to match redactor css.

**Comment by exomarty** [comment]
Whats the problem with this? Let me know in order to fix it

**Comment by drewdotpro** [comment]
I just haven't tried it out yet. It's on my plan for today.

**Comment by drewdotpro** [comment]
I just checked out your code and tested it. I got very strange results:
http://webm.host/cf768/

**Comment by drewdotpro** [comment]
Oops closed by accident

**Comment by yariplus** [comment]
Not all the table tags are in allowedTags server filtering them out.

**Comment by yariplus** [comment]
need tr, td, and th.

**Comment by drewdotpro** [comment]
Merged with some changes to use striped bootstrap tables and to have the tables class in composer match the topics for full WYSIWYG

**Pull request merged**
