### PR TITLE
Add Composer Autocomplete for Emoji

### PR DESCRIPTION
**Pull request by binoalien**

### CODE REVIEW

**Comment by julianlam** [comment]
@barisusakli: @binoalien's changes require modifications to Redactor's source to add the `write` class to the textarea, which makes this a no-go since subsequent updates to the redactor core code would inadvertantly break this functionality.

Suggest passing in a second argument to specify the textarea element, or a css selector... though perhaps you can think of a more elegant way?

**Comment by binoalien** [comment]
@julianlam is this right, now?

**Comment by julianlam** [comment]
@binoalien Maybe you'll just want to restore the original file, since it looks like there are some tab/space issues now 😄

**Comment by binoalien** [comment]
@julianlam i hope it is right, now :)

**Comment by julianlam** [comment]
Yes, this looks good to me.

**Comment by julianlam** [comment]
v1.4.4

**Pull request merged**
