### PR TITLE
Sanitize More, fix #13

### LINKED ISSUE #13: Injecting Javascript, etc
I found several ways to inject arbitrary Javascript into posts. The easiest two being the onmousedown/up/over attributes and using the url() css construct. With some tags, these are not parsed out whatsoever.

You are also not sanitizing on post edit at all, because the passed object is different from what you are expecting.

### PR DESCRIPTION
**Pull request by yariplus**
Fixes things:

Removed wildcard attributes, replaced with list of 'safe' attributes plus 'style'.
~~Added library to parse unsafe 'style' attributes.~~ (Couldn't find a good solution for this.)
Added post edit sanitizing.
You were missing the 'hr' and 'source' tags.

### CODE REVIEW

**Comment by drewdotpro** [comment]
@yariplus thank you for the pull request. Can I enquire where you got the list of safe attributes? I just want to ensure that there are no attributes added by Radactor's WYSIWYG that are then stripped.

**Comment by yariplus** [comment]
I got it from here https://validator.w3.org/feed/docs/warning/SecurityRiskAttr.html

I haven't found any problem using it so far. It does seem a little too restrictive though, maybe this is better: https://pythonhosted.org/feedparser/html-sanitization.html

Even that one seems to be missing some html5 attributes. I'll have to do a more thorough analysis.

**Comment by yariplus** [comment]
I prepared a better organized attribute list that only lists the valid and 'safe' attributes for each tag... and I noticed the library I was using to sanitize css is stripping out a few required attributes.

I think I need a different solution for sanitizing the style attribute.

**Comment by yariplus** [comment]
@drewdotpro This should be good now. It fixes most of the problems. And all of the valid attributes for the previous tag list are entered, so it shouldn't strip out anything needed.

**Pull request merged**
