### PR TITLE
Button Sugar

### LINKED ISSUE #10: How to add a button?
With the default composer its rather easy to add extra buttons, I cant figure how to do it properly with this?
Any tips would be appreciated.
The docs (I think) are showing how to add a button when starting redactor?
You can add one using external api stuff once redactor has started, but then the script has to wait....I know how to do that crap (I like making chrome extensions) but thats bleh.
I can add one using something like this....

```
        if ($ && $.Redactor) {
            $(function() {
                if (!$.Redactor.opts.plugins) $.Redactor.opts.plugins = [];
                $.Redactor.opts.plugins.push('advanced');
                $.Redactor.prototype.advanced = function() {
                    return {
                        init: function() {
                            var button = this.button.add('advanced', 'Advanced');
                            // make your added button as Font Awesome's icon
                            this.button.setAwesome('advanced', 'fa-tasks');
                            this.button.addCallback(button, this.advanced.testButton);
                        },
                        testButton: function(buttonName) {
                            alert(buttonName);
                        }
                    };
                };
                // This is how your MEANT to do it....
                // $('#redactor').redactor({
                //     plugins: ['advanced']
                // });
            });
    }
```

..but I just figured that out by mucking around and cant find it documented anywhere.
I don't know much about hooks yet, but isn't this somewhere that one could be useful?
One to register a plugin to be registered before the start of redactor as it seems your only meant to add them at the start of redactor?

If I'm just missing something simple...I'm sorry, I'm new and impatient ;)

### PR DESCRIPTION
**Pull request by yariplus**
Syntatic Sugar for button adding or option changing. Fixes #10 

Can do as such:

```
$(window).on('action:redactor.load', function (e, redactor) {
    redactor.opts.visual = true;
    redactor.addButton('Alert Me', 'fa-cubes', function (redactor) {
        alert("You are alerted.");
        redactor.selection.wrap('h1');
        redactor.code.sync();
    });
});
```

### CODE REVIEW

**Comment by drewdotpro** [comment]
@yariplus thank you very much for the pull request.
I've asked Imperavi if they'll take the change to redactor into their own code so I don't have to hand merge every redactor update. As soon as I hear back I'll merge accordingly.

**Comment by yariplus** [comment]
Cool.

Actually, if we just change the script loading order, we can put it in client.js

tbh, I'm not sure it's something that belongs in their core code.

**Comment by drewdotpro** [comment]
If Imperavi don't do it then I think that would make a much better PR.
I've already had to make a change to their less file to strip out all their auto-styling but that's just remembering to saw out a big block of less each time. Changes to the redactor library will make my brain hurt every time I have to update redactor.

**Comment by yariplus** [comment]
Okay, I amended it so the new code is in client.js

**Pull request merged**
