### PR TITLE
add server side html sanitizing

### PR DESCRIPTION
**Pull request by philburr**
Fixes issue #5

### CODE REVIEW

**Comment by julianlam** [comment]
Thanks @philburr :smile:

**Comment by drewdotpro** [comment]
For the less file, that gets updated by the redactor team without version control.
It might make more sense for these changes to be in a separate file that can be loaded in over the top to override it.

**Comment by Bitti09** [comment]
I'm getting the following error after applying this pull request:

31/7 12:14 [13518] - error: /admin/plugins/composer-redactor
 TypeError: Object #<Object> has no method 'checkCompatibility'
    at Controllers.renderAdminPage (.../node/node_modules/nodebb-plugin-composer-redactor/lib/controllers.js:8:11)
    at Layer.handle [as handle_request](.../node/node_modules/express/lib/router/layer.js:95:5)
    at next (.../node/node_modules/express/lib/router/route.js:131:13)
    at /.../node/src/middleware/admin.js:51:3
    at /.../node/node_modules/async/lib/async.js:589:17
    at done (/.../node/node_modules/async/lib/async.js:132:19)
    at /.../node/node_modules/async/lib/async.js:32:16
    at /.../node/node_modules/async/lib/async.js:586:21
    at /.../node/src/controllers/api.js:19:5
    at /.../node/src/plugins/hooks.js:96:4

**Comment by philburr** [comment]
@Bitti09 Were you not getting the problem before the patch?  I'm not getting the problem when I go to the Redactor admin page.

**Comment by philburr** [comment]
@drewdotpro I'm not terribly familiar with how the less stuff works.  Alternatively we could lower the z-index of .composer from 10000 to 1000.  I wasn't sure how this would impact other things.  If you merge, let's skip the z-index patch for now until a better solution is done.

**Comment by julianlam** [comment]
To my knowledge, the composer only needs to have a z index lower than the taskbar.

**Comment by drewdotpro** [comment]
@Bitti09 I also had no trouble.
Merged in changes, rolled back 'less file' changes, added them in an override file. 
Thanks @philburr

**Pull request merged**
