### PR TITLE
fix blockquote style

### PR DESCRIPTION
**Pull request by philburr**
This at least matches the blockquote in redactor with the blockquote in the persona theme.

### CODE REVIEW

**Comment by drewdotpro** [comment]
Are you inheriting these styles from somewhere else? If so you may be able to reference them rather than duplicate the style.#theMagicOfLess

**Comment by philburr** [comment]
Hmm, yes.  This is problematic.  The particular styles that I got come from the bootstrap skin Flatly.  Although several of the styles I tested appear similar, it probably should not be assumed so.  I tried to 'Less' style mixin, but apparently it won't work with an external selector.

This isn't really my area of expertise.  How would you go about pulling in the .blockquote styling from an externally referenced CSS file?

**Comment by drewdotpro** [comment]
Ah so it's not coming from a NodeBB or redactor style?
@julianlam do you know if the definition of blockquote style is the same across all nodeBB themes? Ie has the same name. Is it possible to reference it in a plugin's less?

**Comment by drewdotpro** [comment]
I wrote a different fix for this.
I removed Redactor's styles on it's box and wrapped it in spans for topics, posts, content. so it all inherits.

Only thing I need to remember is to strip out the CONTENT STYLES block whenever I update the redactor files

**Pull request closed without merging**
